version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./letsencrypt:/letsencrypt
      - ./deployment/dynamic:/etc/traefik/dynamic
    networks:
      - huginn-net

  frontend:
    image: nginx:alpine
    container_name: frontend
    restart: unless-stopped
    volumes:
      - ./static:/usr/share/nginx/html
    networks:
      - huginn-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`localhost`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

  profile-assembler:
    build:
      context: .
      dockerfile: ./profiler/profile-assembler/Dockerfile
    container_name: profile-assembler
    restart: unless-stopped
    ports:
      - "127.0.0.1:8000:8000"
    networks:
      - huginn-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.profile-assembler.rule=Host(`localhost`) && PathPrefix(`/api`)"
      - "traefik.http.routers.profile-assembler.entrypoints=websecure"
      - "traefik.http.routers.profile-assembler.tls=true"
      - "traefik.http.services.profile-assembler.loadbalancer.server.port=8000"

  tls-collector:
    build:
      context: .
      dockerfile: ./profiler/tls-collector/Dockerfile
    container_name: tls-collector
    restart: unless-stopped
    network_mode: host
    privileged: true
    environment:
      - PROFILER_INTERFACE=wlp0s20f3
    depends_on:
      - profile-assembler

  http-collector:
    build:
      context: .
      dockerfile: ./profiler/http-collector/Dockerfile
    container_name: http-collector
    restart: unless-stopped
    network_mode: host
    privileged: true
    environment:
      - PROFILER_INTERFACE=wlp0s20f3
    depends_on:
      - profile-assembler

networks:
  huginn-net:
    driver: bridge 