services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    command:
      # Global configuration
      - "--log.level=INFO"
      - "--api.dashboard=true"
      # Providers
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"
      # Entrypoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # HTTP/2 configuration
      - "--entrypoints.websecure.http2.maxconcurrentstreams=250"
      - "--serversTransport.insecureSkipVerify=true"
      # HTTP->HTTPS Redirection
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      # Certificate Resolver (Let's Encrypt)
      - "--certificatesresolvers.letsencrypt.acme.email=maxibiandra@gmail.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
      - ./traefik.yml:/etc/traefik/dynamic/traefik.yml:ro
    restart: always
    network_mode: host  # Host mode for external traffic and communication with Huginn
    labels:
      - "traefik.enable=false"

  huginn:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    container_name: huginn
    command:
      - "/app/huginn-api"
      - "--interface"
      - "ens4"  # Primary network interface for external traffic
      - "--bind"
      - "127.0.0.1:3000"  # Bind to localhost for Traefik communication
      - "--ja4-database"
      - "/app/ja4_database.json"
    privileged: true  # Required for packet capture
    restart: always
    volumes:
      - ./ja4_database.json:/app/ja4_database.json:ro
    depends_on:
      - traefik
    network_mode: host  # Host mode for network capture access
    labels:
      - "traefik.enable=true"
      # Router
      - "traefik.http.routers.huginn-app.rule=Host(`huginn-net.duckdns.org`)"
      - "traefik.http.routers.huginn-app.entrypoints=websecure"
      - "traefik.http.routers.huginn-app.service=huginn-app"
      # TLS with HTTP/2 enforcement
      - "traefik.http.routers.huginn-app.tls=true"
      - "traefik.http.routers.huginn-app.tls.certresolver=letsencrypt"
      - "traefik.http.routers.huginn-app.tls.options=my-tls-options@file"
      # Service with explicit localhost connection
      - "traefik.http.services.huginn-app.loadbalancer.server.url=http://127.0.0.1:3000"
      # Dashboard Router (for Traefik's own dashboard)
      - "traefik.http.routers.huginn-dashboard.rule=Host(`huginn-net.duckdns.org`) && PathPrefix(`/dashboard`)"
      - "traefik.http.routers.huginn-dashboard.service=api@internal"
      - "traefik.http.routers.huginn-dashboard.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=admin:$$apr1$$t4i5g2g3$$PklPBOaW8F8aJzsvM4pSg." # Usuario: admin, Pass: huginn
      - "traefik.http.routers.huginn-dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.routers.huginn-dashboard.tls.options=my-tls-options@file"
