version: '3.8'

services:
  traefik:
    image: "traefik:v3.1"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.filename=/etc/traefik/dynamic.yml"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # For local development with self-signed certificates
      - "--log.level=DEBUG"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Traefik dashboard (optional, remove in production)
    volumes:
      # - "./traefik/letsencrypt:/letsencrypt" # Disabled for local development
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.yml:/etc/traefik/dynamic.yml:ro"
      # Mount SSL certificates
      - "./certs/huginn.local.com+2.pem:/etc/ssl/certs/huginn.local.com+2.pem:ro"
      - "./certs/huginn.local.com+2-key.pem:/etc/ssl/private/huginn.local.com+2-key.pem:ro"
    networks:
      - huginn-net

  huginn:
    build:
      context: .. # The build context is the project root
      dockerfile: deployment/Dockerfile # The path to the Dockerfile relative to the context
    container_name: "huginn"
    # network_mode: "host" is the key for the collector to see the host's traffic.
    # The container will share the same network interface as the host machine.
    network_mode: "host"
    # Add capabilities for network capture
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      # Mount the custom JA4 test database
      - "./ja4_test_database.json:/app/ja4db.json:ro"
    command:
      # IMPORTANT: Change 'eth0' to the actual network interface of your host machine.
      # You can find it by running `ip link show` on your host.
      - "./huginn-api"
      - "--interface"
      - "wlp0s20f3"
      - "--bind"
      # Bind to a non-conflicting port on the host, e.g., 3000
      - "0.0.0.0:3000"
      - "--ja4-database"
      - "/app/ja4db.json"
    labels:
      - "traefik.enable=false"  # Disable Docker provider for this service
    depends_on:
      - traefik

networks:
  huginn-net:
    name: huginn-network 