version: '3.8'

services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    command:
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.letsencrypt.acme.email=tu-email@ejemplo.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`TU_DOMINIO.duckdns.org`) && PathPrefix(`/dashboard`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=admin:$$apr1$$t4i5g2g3$$PklPBOaW8F8aJzsvM4pSg." # Usuario: admin, Pass: huginn
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"

  huginn:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    container_name: huginn
    command:
      - "--interface"
      - "eth0"
      - "--bind"
      - "0.0.0.0"
      - "--ja4-database"
      - "/app/ja4_database.json"
    privileged: true
    network_mode: host
    restart: always
    volumes:
      - ./ja4_test_database.json:/app/ja4_database.json:ro
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.huginn-app.rule=Host(`TU_DOMINIO.duckdns.org`)"
      - "traefik.http.routers.huginn-app.tls.certresolver=letsencrypt"
      - "traefik.http.services.huginn-app.loadbalancer.server.port=3000"
      - "traefik.docker.network=bridge"