services:
  traffic-mirror:
    image: alpine:latest
    container_name: traffic-mirror
    command: >
      /bin/sh -c "
        apk add --no-cache iproute2 &&
        tc qdisc del dev lo root 2>/dev/null || true &&
        tc qdisc add dev lo handle 1: root prio &&
        tc filter add dev lo parent 1: protocol ip prio 1 u32 match u32 0 0 action mirred egress mirror dev ens4
      "
    network_mode: host
    privileged: true
    restart: always

  traefik:
    image: traefik:v3.0
    container_name: traefik
    command:
      # Global configuration
      - "--log.level=DEBUG"
      - "--api.dashboard=true"
      # Providers
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"
      # Entrypoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # HTTP->HTTPS Redirection
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      # Certificate Resolver (Let's Encrypt)
      - "--certificatesresolvers.letsencrypt.acme.email=maxibiandra@gmail.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
      - ./traefik.yml:/etc/traefik/dynamic/traefik.yml:ro
    restart: always
    network_mode: host
    labels:
      - "traefik.enable=false"
      - "traefik.http.routers.dashboard.rule=Host(`huginn-net.duckdns.org`) && PathPrefix(`/dashboard`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=admin:$$apr1$$t4i5g2g3$$PklPBOaW8F8aJzsvM4pSg." # Usuario: admin, Pass: huginn
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"

  huginn:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    container_name: huginn
    command:
      - "/app/huginn-api"
      - "--interface"
      - "ens4"
      - "--bind"
      - "0.0.0.0:3000"
      - "--ja4-database"
      - "/app/ja4_database.json"
    privileged: true
    network_mode: host
    restart: always
    volumes:
      - ./ja4_database.json:/app/ja4_database.json:ro
    depends_on:
      - traefik
      - traffic-mirror
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.huginn-app.rule=Host(`huginn-net.duckdns.org`)"
      - "traefik.http.services.huginn-app.loadbalancer.server.port=3000"
      - "traefik.http.routers.huginn-app.tls.certresolver=letsencrypt"
      - "traefik.http.routers.huginn-app.tls.options=default"